# Generated by Django 6.0.8 on 2026-09-06 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('effective_from', models.DateTimeField()),
                ('source', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('approver', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='GeographicNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('level', models.CharField(choices=[('country', 'Pays'), ('department', 'Département'), ('arrondissement', 'Arrondissement'), ('commune', 'Commune'), ('section_communale', 'Section communale'), ('locality', 'Localité'), ('electoral_district', 'Circonscription électorale'), ('voting_center', 'Centre de vote'), ('polling_station', 'Bureau de vote')], max_length=32)),
                ('name', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='geography.geographicnode')),
                ('geo_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='geography.geoversion')),
            ],
        ),
        migrations.CreateModel(
            name='VotingCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.JSONField(default=dict)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geo_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.geoversion')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voting_centers', to='geography.geographicnode')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.JSONField(default=dict)),
                ('capacity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geo_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.geoversion')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='geography.votingcenter')),
            ],
        ),
        migrations.AddIndex(
            model_name='geographicnode',
            index=models.Index(fields=['level', 'geo_version'], name='geography_g_level_aa3667_idx'),
        ),
        migrations.AddConstraint(
            model_name='geographicnode',
            constraint=models.UniqueConstraint(fields=('code', 'geo_version'), name='uniq_node_per_version'),
        ),
        migrations.AddConstraint(
            model_name='votingcenter',
            constraint=models.UniqueConstraint(fields=('node', 'code'), name='uniq_center_per_node'),
        ),
        migrations.AddConstraint(
            model_name='pollingstation',
            constraint=models.UniqueConstraint(fields=('center', 'code'), name='uniq_station_per_center'),
        ),
    ]
