# Generated by Django 6.0.8 on 2026-09-06 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('geography', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=64)),
                ('commune', models.CharField(max_length=64)),
                ('center_latitude', models.FloatField(blank=True, null=True)),
                ('center_longitude', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.PositiveIntegerField(default=5000)),
                ('polygon_geojson', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('device_model', models.CharField(max_length=64)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Enregistré'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REVOKED', 'Révoqué')], default='REGISTERED', max_length=16)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('battery_level', models.PositiveIntegerField(default=100)),
                ('app_version', models.CharField(default='1.0.0', max_length=32)),
                ('assigned_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='geography.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=16)),
                ('target_type', models.CharField(max_length=16)),
                ('reason', models.CharField(max_length=256)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('audit_hash', models.CharField(max_length=64)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='elections.election')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='registry.elector')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='geography.pollingstation')),
                ('target_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='geography.pollingstation')),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='PollingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PREPARED', 'Préparée'), ('OPEN', 'Ouverte'), ('CLOSED', 'Fermée'), ('TABULATED', 'Dépouillée')], default='PREPARED', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ballots_cast', models.PositiveIntegerField(default=0)),
                ('pv_received', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polling_sessions', to='elections.election')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='geography.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('validated', models.BooleanField(default=False)),
                ('anomaly_flags', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_records', to='operations.pollingsession')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_type', models.CharField(choices=[('FIXED', 'Fixe'), ('NOMADIC', 'Nomade'), ('VIRTUAL', 'Virtuel (Online-Z)')], default='FIXED', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='elections.election')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='registry.elector')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elector_assignments', to='geography.pollingstation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('election', 'elector'), name='uniq_active_elector_assignment_per_election')],
            },
        ),
        migrations.AddConstraint(
            model_name='pollingsession',
            constraint=models.UniqueConstraint(fields=('election', 'station'), name='uniq_session_per_station'),
        ),
    ]
