# Generated by Django 6.0.8 on 2026-09-06 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandataire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('cin', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo_url', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=16, unique=True)),
                ('name', models.JSONField(default=dict)),
                ('legal_reference', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REVOKED', 'Révoqué')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
                ('ballot_index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('UNDER_REVIEW', 'En revue'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('PUBLISHED', 'Publiée'), ('WITHDRAWN', 'Retirée')], default='DRAFT', max_length=16)),
                ('photo_key', models.CharField(blank=True, max_length=128)),
                ('documents', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('territory_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.geographicnode')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='candidates.party')),
            ],
            options={
                'ordering': ['ballot_index'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('represented_type', models.CharField(choices=[('PARTY', 'Parti politique'), ('CANDIDATE', 'Candidat indépendant')], default='PARTY', max_length=16)),
                ('mode', models.CharField(choices=[('PHYSICAL', 'Bureau physique'), ('ONLINE', 'Surveillance en ligne'), ('BOTH', 'Hybride (Physique + En ligne)')], default='PHYSICAL', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PROPOSED', 'Proposé'), ('PENDING_CEP_REVIEW', 'En examen CEP'), ('APPROVED', 'Approuvé'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REVOKED', 'Révoqué'), ('EXPIRED', 'Expiré'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=32)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('commune', models.CharField(blank=True, max_length=64)),
                ('assigned_stations', models.JSONField(blank=True, default=list)),
                ('badge_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='candidates.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='elections.election')),
                ('mandataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='candidates.mandataire')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='candidates.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('election', 'post', 'territory_node', 'ballot_index'), name='uniq_candidate_ballot_slot'),
        ),
    ]
