# Generated by Django 6.0.8 on 2026-09-06 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.JSONField(default=dict)),
                ('election_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONFIGURATION', 'Configuration'), ('REGISTRATION', 'Enregistrement'), ('CANDIDATE_VALIDATION', 'Validation des candidatures'), ('READY', 'Prêt'), ('OPEN', 'Ouverte'), ('SUSPENDED', 'Suspendue'), ('CLOSED', 'Fermée'), ('TABULATION', 'Tabulation'), ('PROVISIONAL_RESULTS', 'Résultats provisoires'), ('FINAL_VALIDATION', 'Validation finale'), ('FINAL_RESULTS', 'Résultats définitifs'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=32)),
                ('legal_configuration', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rules', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='election_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='TerritoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=32)),
                ('assign', models.CharField(max_length=32)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_rules', to='elections.election')),
            ],
            options={
                'ordering': ['ordering'],
                'constraints': [models.UniqueConstraint(fields=('election', 'post'), name='uniq_territory_rule_per_post')],
            },
        ),
    ]
