# Generated by Django 6.0.8 on 2026-09-06 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ref', models.CharField(max_length=128)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('context', models.CharField(blank=True, max_length=128)),
                ('object_ref', models.CharField(blank=True, max_length=128)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(db_index=True, max_length=64)),
                ('previous_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['actor_ref', 'occurred_at'], name='audit_audit_actor_r_e15523_idx')],
            },
        ),
    ]
