# Generated by Django 6.0.8 on 2026-09-06 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('options', models.JSONField(default=list)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='elections.election')),
            ],
            options={
                'ordering': ['sealed_at'],
            },
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electoral_reference', models.CharField(max_length=40, unique=True)),
                ('identity_hash', models.CharField(db_index=True, max_length=64)),
                ('registration_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_VERIFICATION', 'En attente de vérification'), ('REGISTERED', 'Enregistré'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('INACTIVE', 'Inactif'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=32)),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'Éligible'), ('NOT_ELIGIBLE', 'Non éligible'), ('PENDING', 'En attente'), ('REVOKED', 'Révoqué')], default='PENDING', max_length=32)),
                ('status_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.pollingstation')),
                ('registration_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geography.votingcenter')),
                ('territorial_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electors', to='geography.geographicnode')),
            ],
            options={
                'ordering': ['electoral_reference'],
            },
        ),
        migrations.CreateModel(
            name='RecordedVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_reference', models.CharField(max_length=64, unique=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='registry.ballot')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_votes', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Éligible'), ('NOT_ELIGIBLE', 'Non éligible'), ('PENDING', 'En attente'), ('REVOKED', 'Révoqué')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='elections.election')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='registry.elector')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('elector', 'election'), name='uniq_eligibility_per_election')],
            },
        ),
        migrations.CreateModel(
            name='ParticipationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('ISSUED', 'Émise'), ('USED', 'Utilisée'), ('CANCELLED', 'Annulée'), ('REVOKED', 'Révoquée')], default='ISSUED', max_length=16)),
                ('anti_replay_hash', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_tokens', to='elections.election')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_tokens', to='registry.elector')),
                ('issuing_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.pollingstation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'elector'), name='uniq_participation_per_election')],
            },
        ),
    ]
