# Generated by Django 6.0.8 on 2026-09-06 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('device', 'Appareil'), ('network', 'Réseau'), ('power', 'Alimentation'), ('identity', 'Identité'), ('eligibility', 'Éligibilité'), ('security', 'Sécurité'), ('hardware', 'Matériel'), ('software', 'Logiciel'), ('station_inaccessible', 'Bureau inaccessible'), ('operational', 'Opérationnel'), ('sync_anomaly', 'Anomalie de synchronisation'), ('electoral', 'Incident électoral')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Créé'), ('CLASSIFIED', 'Classifié'), ('ASSIGNED', 'Assigné'), ('INVESTIGATING', 'Investigué'), ('RESOLVED', 'Résolu'), ('VERIFIED', 'Vérifié'), ('ARCHIVED', 'Archivé')], default='OPEN', max_length=16)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField()),
                ('event_log', models.JSONField(default=list)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
